### PR TITLE
Adds block context on respond_to method

### PR DESCRIPTION
**Pull request by dlinch**
Address [Issue 8](https://github.com/jejacks0n/bitbot/issues/8)
Updated ReadMe, including some markdown linting.

Update `respond_to` method to take a block whose return value is available within a route so regex isn't the only way to pass data through.

### CODE REVIEW

**Comment by dlinch** [comment]
@jejacks0n If you add the hacktoberfest topic to the repo then I get credit for hacktoberfest for this PR :)

**Comment by jejacks0n** [comment]
You should do that do I know what you mean. You’re a collaborator now.

**Comment by dlinch** [comment]
@jejacks0n Can I merge this bad boy then?

**Comment by jejacks0n** [comment]
Of course!

**Comment by mikepack** [comment]
giphy

**Pull request merged**
